#!/usr/bin/env python3
"""
Generate version.h header file from GitVersion output
"""
Import("env")
import subprocess
import json
from datetime import datetime, timezone

print("=" * 60)
print("Generating version information...")
print("=" * 60)

# Try to get version from GitVersion
version_info = {
    "semver": "0.0.0-dev",
    "fullsemver": "0.0.0-dev",
    "branch": "unknown",
    "sha": "unknown",
    "short_sha": "unknown",
    "build_timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
}

try:
    # Run gitversion
    result = subprocess.run(
        ["gitversion"],
        capture_output=True,
        text=True,
        check=False,
        cwd=env.get("PROJECT_DIR")
    )
    
    if result.returncode == 0:
        gitversion_data = json.loads(result.stdout)
        version_info["semver"] = gitversion_data.get("SemVer", "0.0.0-dev")
        version_info["fullsemver"] = gitversion_data.get("FullSemVer", "0.0.0-dev")
        version_info["branch"] = gitversion_data.get("BranchName", "unknown")
        version_info["sha"] = gitversion_data.get("Sha", "unknown")
        version_info["short_sha"] = gitversion_data.get("ShortSha", "unknown")
        print(f"✓ GitVersion: {version_info['semver']}")
        print(f"  Branch: {version_info['branch']}")
        print(f"  Commit: {version_info['short_sha']}")
    else:
        print("⚠ GitVersion not available, using git fallback")
        # Fallback to git commands
        try:
            # Get current branch
            branch_result = subprocess.run(
                ["git", "rev-parse", "--abbrev-ref", "HEAD"],
                capture_output=True,
                text=True,
                check=True,
                cwd=env.get("PROJECT_DIR")
            )
            version_info["branch"] = branch_result.stdout.strip()
            
            # Get commit SHA
            sha_result = subprocess.run(
                ["git", "rev-parse", "HEAD"],
                capture_output=True,
                text=True,
                check=True,
                cwd=env.get("PROJECT_DIR")
            )
            version_info["sha"] = sha_result.stdout.strip()
            version_info["short_sha"] = version_info["sha"][:7]
            
            # Use branch+sha as version
            version_info["semver"] = f"0.0.0-{version_info['branch']}-{version_info['short_sha']}"
            version_info["fullsemver"] = version_info["semver"]
            
            print(f"✓ Git fallback: {version_info['semver']}")
        except subprocess.CalledProcessError:
            print("⚠ Git also not available, using default values")
            
except Exception as e:
    print(f"⚠ Error getting version info: {e}")
    print("  Using default values")

# Generate header file
header_content = f"""/**
 * Auto-generated version information
 * Generated at: {version_info['build_timestamp']}
 * DO NOT EDIT THIS FILE MANUALLY
 */

#ifndef VERSION_H
#define VERSION_H

#define VERSION_SEMVER "{version_info['semver']}"
#define VERSION_FULL "{version_info['fullsemver']}"
#define VERSION_BRANCH "{version_info['branch']}"
#define VERSION_SHA "{version_info['sha']}"
#define VERSION_SHORT_SHA "{version_info['short_sha']}"
#define VERSION_BUILD_TIMESTAMP "{version_info['build_timestamp']}"

#endif // VERSION_H
"""

# Write to include directory
include_dir = env.subst("$PROJECT_DIR/include")
version_file = f"{include_dir}/version.h"

with open(version_file, "w") as f:
    f.write(header_content)

print(f"✓ Generated: {version_file}")
print("=" * 60)
