[env:atom_s3_lite]
platform = espressif32
board = m5stack-atom
framework = arduino

monitor_speed = 115200

lib_deps =
    TMCStepper
    bblanchon/ArduinoJson @ ^7.1.0

build_flags =
    -D WIFI_SSID="your_wifi_ssid"
    -D WIFI_PASSWORD="your_wifi_password"
    -D MDNS_NAME="webmotor"
