/**
 * Auto-generated version information
 * Generated at: 2026-02-22T13:20:28Z
 * DO NOT EDIT THIS FILE MANUALLY
 */

#ifndef VERSION_H
#define VERSION_H

#define VERSION_SEMVER "0.2.0-add-cloud.1"
#define VERSION_FULL "0.2.0-add-cloud.1+2"
#define VERSION_BRANCH "add_cloud"
#define VERSION_SHA "76ce2488bc76463595c35dcc2d6c61ec3a499952"
#define VERSION_SHORT_SHA "76ce248"
#define VERSION_BUILD_TIMESTAMP "2026-02-22T13:20:28Z"

#endif // VERSION_H
