/**
 * Auto-generated version information
 * Generated at: 2026-02-22T13:36:05Z
 * DO NOT EDIT THIS FILE MANUALLY
 */

#ifndef VERSION_H
#define VERSION_H

#define VERSION_SEMVER "0.2.0-add-cloud.1"
#define VERSION_FULL "0.2.0-add-cloud.1+6"
#define VERSION_BRANCH "add_cloud"
#define VERSION_SHA "8f20d5971ec5e8ca5d46d08795ad774e95a29fb7"
#define VERSION_SHORT_SHA "8f20d59"
#define VERSION_BUILD_TIMESTAMP "2026-02-22T13:36:05Z"

#endif // VERSION_H
